// Generated by ScreenFlow Studio from a validated Blueprint. Edit freely: it is yours now.
import type { ReactNode } from 'react'
import { Stack } from '@/primitives'
import { InteractivityButton } from '@/ui-kit/InteractivityButton'
import { InteractivityMenu } from '@/ui-kit/InteractivityMenu'
import { MainMenu } from '@/ui-kit/MainMenu'
import { Screen } from '@/ui-kit/Screen'

/**
 * HomeProgramacao — layer model `home-buttons-left`, level 1.
 */
export function HomeProgramacao(): ReactNode {
  return (
    <Screen model="home-buttons-left" level={1} focusSide="left">
      <Stack direction="column" justify="end" gap="sm" padding="none" grow>
        <Stack direction="column" justify="end" gap="2xl">
          <InteractivityMenu align="start">
            <InteractivityButton
              overline="13:00"
              live
              title="Jornal da Tarde"
              interactionState="default"
            />
            <InteractivityButton
              overline="14:30"
              title="Cinema em Casa"
              interactionState="default"
            />
            <InteractivityButton
              overline="16:00"
              title="Novela das Seis"
              interactionState="default"
            />
          </InteractivityMenu>
          <MainMenu
            focusedItem="schedule"
            miscellaneousTitle="Previsão do tempo"
            miscellaneousSubtitle="São Paulo, SP"
            programTitle="Copa do Mundo: Equador x Argentina"
            programSubtitle="A seguir Central da Copa"
          />
        </Stack>
      </Stack>
    </Screen>
  )
}

export default HomeProgramacao
