export default {
  start: 'home-bug',
  transitions: [
    { from: 'home-bug', key: 'left', to: 'home-program' },
    { from: 'home-program', key: 'right', to: 'home-bug' },
    { from: 'home-program', key: 'left', to: 'home-misc' },
    { from: 'home-misc', key: 'right', to: 'home-program' },
    { from: 'home-misc', key: 'left', to: 'home-schedule' },
    { from: 'home-schedule', key: 'right', to: 'home-misc' },
    { from: 'home-schedule', key: 'left', to: 'home-login' },
    { from: 'home-login', key: 'right', to: 'home-schedule' },
    { from: 'home-misc', key: 'up', to: 'rail-misc' },
    { from: 'rail-misc', key: 'down', to: 'home-misc' },
    { from: 'rail-misc', key: 'enter', to: 'detail' },
    { from: 'detail', key: 'up', to: 'detail-card' },
    { from: 'detail-card', key: 'down', to: 'detail' },
    { from: 'home-program', key: 'back', to: 'home-bug' },
    { from: 'home-misc', key: 'back', to: 'home-bug' },
    { from: 'home-schedule', key: 'back', to: 'home-bug' },
    { from: 'home-login', key: 'back', to: 'home-bug' },
    { from: 'home-bug', key: 'back', to: 'hidden' },
  ],
}
