/**
 * `npm run guides:build` — writes web/protos/generated/tokens.md and rules.md, the
 * reference a designer's Claude Code reads, from tokens/tokens.json and rules.ts.
 *
 * `npm run guides:check` (`--check`) writes nothing and exits 1 when a committed
 * file differs from regeneration. `npm run tokens:check` runs it too.
 * Output is sorted, so the order of entries in either source does not matter.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { RULES } from '../src/shared/design-system/rules'
import { ruleScope } from '../src/shared/design-system/deviations'
import { COMMENT_TAGS } from '../src/shared/export/commentGrammar'
import { hexWithAlpha, isAlpha } from '../src/shared/design-system/color-alpha'
import { collectTokens, CSS_EXTENSION, cssVarName, NAME_FAMILIES, textClassName, TOKENS_SOURCE } from './tokens/compile'

export const GUIDE_FILES = { tokens: 'web/protos/generated/tokens.md', rules: 'web/protos/generated/rules.md' } as const

const HEADER =
  '<!-- GENERATED by scripts/build-guides.ts from tokens/tokens.json and src/shared/design-system/rules.ts. Do not edit; run npm run guides:build. -->'

/** Families with a prop type the kit declares by hand in `src/primitives/tokens.ts` (SizeRole, RadiusRole). */
const EXTRA_FAMILIES = [
  { type: 'SizeRole', prefix: '--dimension-size-semantic-' },
  { type: 'RadiusRole', prefix: '--dimension-radius-semantic-' },
]

const cmp = (a: string, b: string): number => (a < b ? -1 : a > b ? 1 : 0)
const cell = (s: string): string => s.replace(/\|/g, '\\|').replace(/\n/g, ' ')

type Json = Record<string, unknown>
type Tok = ReturnType<typeof collectTokens>[number]

export function tokensGuide(root: unknown): string {
  const all = collectTokens(root as Json)
  const byPath = new Map(all.map((t) => [t.path.join('.'), t]))
  const resolve = (v: unknown, seen: string[] = []): unknown => {
    if (typeof v === 'string') {
      const m = /^\{([^}]+)\}$/.exec(v)
      if (!m) return v
      if (seen.includes(m[1])) throw new Error(`alias cycle at ${m[1]}`)
      const target = byPath.get(m[1])
      return target && literalOf(target, [...seen, m[1]])
    }
    if (Array.isArray(v)) return v.map((x) => resolve(x, seen))
    if (v && typeof v === 'object') return Object.fromEntries(Object.entries(v).map(([k, x]) => [k, resolve(x, seen)]))
    return v
  }
  /** A token's resolved value; an alpha variant shows the `#RRGGBBAA` of its base, not the bare base. */
  const literalOf = (t: Tok, seen: string[] = []): unknown => {
    const value = resolve(t.value, seen)
    const hint = t.extensions?.[CSS_EXTENSION]
    const alpha = hint && typeof hint === 'object' ? (hint as Json).alpha : undefined
    return typeof value === 'string' && isAlpha(alpha) ? (hexWithAlpha(value, alpha) ?? value) : value
  }
  const show = (v: unknown): string => (typeof v === 'string' ? v : JSON.stringify(v, (_, x) => (x && typeof x === 'object' && !Array.isArray(x) ? Object.fromEntries(Object.entries(x).sort(([a], [b]) => cmp(a, b))) : x)))

  const screenName = (t: Tok): string => {
    const css = cssVarName(t.path)
    if (t.type === 'typography') return `\`Text variant="${textClassName(t.path).replace(/^text-/, '')}"\``
    for (const f of [...NAME_FAMILIES, ...EXTRA_FAMILIES]) {
      if (!css.startsWith(f.prefix)) continue
      const name = css.slice(f.prefix.length)
      const asText = f.type === 'StatusColor' ? ` or \`TextColor\` \`status-${name}\`` : ''
      return `\`${f.type}\` \`${name}\`${asText}`
    }
    return ''
  }

  const groups = new Map<string, Tok[]>()
  for (const t of all) {
    if (t.path.includes('core')) continue // core tokens exist only for other tokens to point at
    const g = t.path.slice(0, 2).join('.')
    groups.set(g, [...(groups.get(g) ?? []), t])
  }
  const out = [
    HEADER,
    '',
    '# Tokens',
    '',
    'Semantic and layout tokens only; core tokens are never named by a screen. "Screen name" is the value a kit prop takes (its type in `src/primitives/token-names.ts` or `tokens.ts`); blank means no kit prop takes it.',
    'Spacing and radius steps are core scales: use the `GridSpacing` and `RadiusStep` props of the kit.',
  ]
  for (const g of [...groups.keys()].sort(cmp)) {
    out.push('', `## ${g}`, '', '| Path | Value | Screen name |', '| --- | --- | --- |')
    for (const t of groups.get(g)!.sort((a, b) => cmp(a.path.join('.'), b.path.join('.')))) {
      out.push(`| \`${t.path.join('.')}\` | ${cell(show(literalOf(t)))} | ${cell(screenName(t))} |`)
    }
  }
  return out.join('\n') + '\n'
}

interface RuleLike {
  id: string
  title: string
  statement: string
  flexibility: string
  appliesTo?: readonly string[]
}

export function rulesGuide(rules: readonly RuleLike[], scope: (id: string) => string = ruleScope): string {
  const out = [HEADER, '', '# Rules', '']
  const titles = { law: 'Laws (never bypassable)', pattern: 'Patterns (breakable in Exploratory mode, declared)', convention: 'Conventions (breaking one only produces a note)' }
  for (const level of ['law', 'pattern', 'convention'] as const) {
    out.push(`## ${titles[level]}`, '')
    for (const r of rules.filter((x) => x.flexibility === level).sort((a, b) => cmp(a.id, b.id))) {
      out.push(`### \`${r.id}\` ${r.title}`, '', r.statement, '')
      if (r.appliesTo?.length) out.push(`Applies to: ${r.appliesTo.map((c) => `\`${c}\``).join(', ')}`, '')
    }
  }
  out.push('## How to declare', '')
  for (const c of COMMENT_TAGS) {
    out.push(`### \`${c.tag}\``, '', `Form: \`${c.form}\``, '', c.meaning, '', `- On a node: ${c.node}`, `- On the screen: ${c.screen}`, '')
  }
  const patterns = rules.filter((r) => r.flexibility === 'pattern').map((r) => r.id)
  const list = (s: string): string => patterns.filter((id) => scope(id) === s).sort(cmp).map((id) => `\`${id}\``).join(', ') || 'none'
  out.push(
    '### Where each pattern is declared',
    '',
    `- On the node where it breaks (a screen-level declaration is an error): ${list('node')}`,
    `- On the screen, or on the root node: ${list('screen')}`,
    '',
  )
  return out.join('\n').replace(/\n+$/, '\n')
}

export function buildGuides(tokensJson: unknown, rules: readonly RuleLike[] = RULES as unknown as RuleLike[]) {
  return { tokens: tokensGuide(tokensJson), rules: rulesGuide(rules) }
}

function main(): void {
  const ROOT = fileURLToPath(new URL('..', import.meta.url))
  const check = process.argv.includes('--check')
  const built = buildGuides(JSON.parse(readFileSync(join(ROOT, TOKENS_SOURCE), 'utf8')))
  const stale: string[] = []
  for (const key of ['tokens', 'rules'] as const) {
    const file = join(ROOT, GUIDE_FILES[key])
    let current = ''
    try {
      current = readFileSync(file, 'utf8')
    } catch {
      // Missing counts as stale.
    }
    if (current === built[key]) continue
    stale.push(GUIDE_FILES[key])
    if (!check) {
      mkdirSync(join(file, '..'), { recursive: true })
      writeFileSync(file, built[key])
    }
  }
  if (check) {
    if (stale.length) {
      console.error(`Stale guide — run \`npm run guides:build\`:\n${stale.map((f) => `  ${f}`).join('\n')}`)
      process.exit(1)
    }
    console.log('Guides are up to date with tokens.json and rules.ts.')
  } else {
    console.log(stale.length ? `Wrote ${stale.join(', ')}` : 'Guides already up to date.')
  }
}

if (!process.env.VITEST) main()
