// GENERATED by `npm run tokens:build` from tokens/tokens.json — do not edit.
//
// The prop names primitives take, written out so Storybook's docgen can read them.

/** A step of the spacing scale. */
export type SpacingStep =
  | 'none'
  | '3xs'
  | '2xs'
  | 'xs'
  | 'sm'
  | 'md'
  | 'lg'
  | 'xl'
  | '2xl'
  | '3xl'
  | '4xl'
  | '5xl'
  | '6xl'

/** A step of the radius scale. */
export type RadiusStep =
  | 'none'
  | 'xs'
  | 'sm'
  | 'md'
  | 'lg'
  | 'xl'
  | '2xl'
  | '4xl'
  | '5xl'
  | '6xl'
  | '7xl'
  | '8xl'
  | '9xl'
  | '10xl'
  | 'full'

/** A functional background role. */
export type SurfaceColor =
  | 'primary'
  | 'elevated'
  | 'overlay'
  | 'translucent'
  | 'tint'

/** A functional border role. */
export type BorderColor =
  | 'subtle'
  | 'default'

/** A status colour. */
export type StatusColor =
  | 'error'
  | 'success'
  | 'warning'
  | 'live'

/** A functional text role. */
export type TextRole =
  | 'primary'
  | 'secondary'
  | 'subtle'
  | 'inverse'
  | 'muted'

/** A semantic opacity role. */
export type OpacityRole =
  | 'hidden'
  | 'overlay-minimal'
  | 'image-subdued'
  | 'shadow-subtle'
  | 'background-subtle'
  | 'border-subtle'
  | 'content-muted'
  | 'overlay'
  | 'text-secondary'
  | 'statistics-vector'
  | 'illumination-strong'
  | 'title'
  | 'visible'
  | 'focus-glow'
  | 'state-disabled'

/** A spacing step on the layout grid (frameSpec: multiples of 8, plus 4 and 12). */
export type GridSpacing =
  | 'none'
  | '3xs'
  | '2xs'
  | 'xs'
  | 'sm'
  | 'lg'
  | 'xl'
  | '2xl'
  | '3xl'
  | '4xl'
  | '5xl'
  | '6xl'

/** A text role, or a status colour as `status-<name>`. */
export type TextColor =
  | 'primary'
  | 'secondary'
  | 'subtle'
  | 'inverse'
  | 'muted'
  | 'status-error'
  | 'status-success'
  | 'status-warning'
  | 'status-live'
